model_name: mobilenet_v2
modality: audio

num_classes: 2
pretrained: true
use_custom_weights: true

input:
  size: [224, 224]
  channels: 3

spectrogram:
  type: mel
  sample_rate: 16000
  n_mels: 128
  hop_length: 512

labels:
  0: fake
  1: real
